"""Private PostgreSQL schema. Engine objects never become ORM entities."""
from sqlalchemy import (MetaData, Table, Column, Text, Integer, BigInteger, Boolean,
                        DateTime, LargeBinary, ForeignKey, ForeignKeyConstraint,
                        UniqueConstraint, CheckConstraint, Index)
from sqlalchemy.dialects.postgresql import UUID, JSONB

metadata = MetaData()

rooms = Table("rooms", metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column("room_code", Text, nullable=False, unique=True),
    Column("status", Text, nullable=False),
    Column("max_players", Integer, nullable=False),
    Column("host_room_player_id", UUID(as_uuid=True), nullable=False),
    Column("current_match_id", UUID(as_uuid=True)),
    Column("match_no", BigInteger, nullable=False),
    Column("tick", BigInteger, nullable=False),
    Column("config", JSONB, nullable=False),
    Column("map_revision", BigInteger, nullable=False),
    Column("config_revision", BigInteger, nullable=False),
    Column("durable_revision", BigInteger, nullable=False),
    Column("chat_revision", BigInteger, nullable=False),
    Column("chat_history", JSONB, nullable=False),
    Column("is_test", Boolean, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("last_activity_at", DateTime(timezone=True), nullable=False),
    Column("closed_at", DateTime(timezone=True)),
    Column("expires_at", DateTime(timezone=True)),
    CheckConstraint("max_players BETWEEN 2 AND 6", name="room_capacity"),
    CheckConstraint("status IN ('lobby','in_match','closed','expired','abandoned','quarantined')", name="room_status"),
    ForeignKeyConstraint(["host_room_player_id", "id"], ["room_players.id", "room_players.room_id"], name="room_host", deferrable=True, initially="DEFERRED", use_alter=True),
    ForeignKeyConstraint(["current_match_id", "id"], ["matches.id", "matches.room_id"], name="room_current_match", deferrable=True, initially="DEFERRED", use_alter=True),
)
Index("rooms_recovery", rooms.c.status, rooms.c.last_activity_at)

room_players = Table("room_players", metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column("room_id", UUID(as_uuid=True), ForeignKey("rooms.id"), nullable=False),
    Column("name", Text, nullable=False),
    Column("color", Text, nullable=False),
    Column("current_pid", Integer),
    Column("status", Text, nullable=False),
    Column("joined_at", DateTime(timezone=True), nullable=False),
    Column("last_seen_at", DateTime(timezone=True), nullable=False),
    Column("removed_at", DateTime(timezone=True)),
    UniqueConstraint("id", "room_id"),
    UniqueConstraint("room_id", "current_pid"),
    CheckConstraint("status IN ('active','retired','revoked')", name="member_status"),
    CheckConstraint("current_pid IS NULL OR current_pid BETWEEN 0 AND 5", name="member_pid"),
    CheckConstraint("color IN ('red','blue','orange','white','green','purple')", name="member_color"),
)
Index("room_active_color", room_players.c.room_id, room_players.c.color, unique=True, postgresql_where=room_players.c.status == "active")
Index("room_active_name", room_players.c.room_id, room_players.c.name, unique=True, postgresql_where=room_players.c.status == "active")

seat_tokens = Table("seat_tokens", metadata,
    Column("room_player_id", UUID(as_uuid=True), ForeignKey("room_players.id"), primary_key=True),
    Column("token_hash", LargeBinary, nullable=False, unique=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("revoked_at", DateTime(timezone=True)),
    CheckConstraint("octet_length(token_hash) = 32", name="credential_hash_length"),
)

matches = Table("matches", metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column("room_id", UUID(as_uuid=True), ForeignKey("rooms.id"), nullable=False),
    Column("match_no", BigInteger, nullable=False),
    Column("status", Text, nullable=False),
    Column("tick", BigInteger, nullable=False),
    Column("map_id", Text, nullable=False),
    Column("map_name", Text, nullable=False),
    Column("settings", JSONB, nullable=False),
    Column("is_test", Boolean, nullable=False),
    Column("latest_snapshot_id", UUID(as_uuid=True)),
    Column("winner_match_player_id", UUID(as_uuid=True)),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("finished_at", DateTime(timezone=True)),
    UniqueConstraint("room_id", "match_no"), UniqueConstraint("id", "room_id"),
    CheckConstraint("status IN ('active','finished','superseded','abandoned','quarantined')", name="match_status"),
    ForeignKeyConstraint(["latest_snapshot_id", "id"], ["game_snapshots.id", "game_snapshots.match_id"], name="match_head", deferrable=True, initially="DEFERRED", use_alter=True),
    ForeignKeyConstraint(["winner_match_player_id", "id"], ["match_players.id", "match_players.match_id"], name="match_winner", deferrable=True, initially="DEFERRED", use_alter=True),
)
Index("one_active_match", matches.c.room_id, unique=True, postgresql_where=matches.c.status == "active")

match_players = Table("match_players", metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column("room_id", UUID(as_uuid=True), nullable=False),
    Column("match_id", UUID(as_uuid=True), nullable=False),
    Column("room_player_id", UUID(as_uuid=True), nullable=False),
    Column("pid", Integer, nullable=False),
    Column("name", Text, nullable=False), Column("color", Text, nullable=False),
    Column("consumed_seq", BigInteger, nullable=False),
    Column("final_vp", Integer),
    UniqueConstraint("match_id", "pid"), UniqueConstraint("match_id", "room_player_id"), UniqueConstraint("id", "match_id"),
    ForeignKeyConstraint(["match_id", "room_id"], ["matches.id", "matches.room_id"]),
    ForeignKeyConstraint(["room_player_id", "room_id"], ["room_players.id", "room_players.room_id"]),
    CheckConstraint("pid BETWEEN 0 AND 5 AND consumed_seq >= 0", name="match_player_sequence"),
)

game_snapshots = Table("game_snapshots", metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column("match_id", UUID(as_uuid=True), ForeignKey("matches.id"), nullable=False),
    Column("revision", BigInteger, nullable=False),
    Column("tick", BigInteger, nullable=False),
    Column("snapshot_version", Integer, nullable=False),
    Column("engine_compatibility", Integer, nullable=False),
    Column("payload", JSONB, nullable=False),
    Column("checksum", LargeBinary, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("id", "match_id"), UniqueConstraint("match_id", "revision"),
)

command_receipts = Table("command_receipts", metadata,
    Column("match_player_id", UUID(as_uuid=True), ForeignKey("match_players.id"), primary_key=True),
    Column("seq", BigInteger, primary_key=True),
    Column("cmd_id", Text, nullable=False), Column("payload_hash", LargeBinary, nullable=False),
    Column("outcome", Text, nullable=False), Column("error_code", Text),
    Column("result_tick", BigInteger, nullable=False), Column("result_revision", BigInteger, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("match_player_id", "cmd_id"),
    CheckConstraint("outcome IN ('accepted','rejected')", name="receipt_outcome"),
)

room_operations = Table("room_operations", metadata,
    Column("room_id", UUID(as_uuid=True), ForeignKey("rooms.id"), primary_key=True),
    Column("request_id", Text, primary_key=True),
    Column("room_player_id", UUID(as_uuid=True), nullable=False),
    Column("kind", Text, nullable=False), Column("payload_hash", LargeBinary, nullable=False),
    Column("expected_epoch", BigInteger, nullable=False), Column("result_epoch", BigInteger, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    ForeignKeyConstraint(["room_player_id", "room_id"], ["room_players.id", "room_players.room_id"]),
)
