"""durable multiplayer rooms and match heads"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = 'ab68cc7c6ebb'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_code', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('host_room_player_id', sa.UUID(), nullable=False),
    sa.Column('current_match_id', sa.UUID(), nullable=True),
    sa.Column('match_no', sa.BigInteger(), nullable=False),
    sa.Column('tick', sa.BigInteger(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('map_revision', sa.BigInteger(), nullable=False),
    sa.Column('config_revision', sa.BigInteger(), nullable=False),
    sa.Column('durable_revision', sa.BigInteger(), nullable=False),
    sa.Column('chat_revision', sa.BigInteger(), nullable=False),
    sa.Column('chat_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('lobby','in_match','closed','expired','abandoned','quarantined')", name='room_status'),
    sa.CheckConstraint('max_players BETWEEN 2 AND 6', name='room_capacity'),
    sa.ForeignKeyConstraint(['current_match_id', 'id'], ['matches.id', 'matches.room_id'], name='room_current_match', initially='DEFERRED', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['host_room_player_id', 'id'], ['room_players.id', 'room_players.room_id'], name='room_host', initially='DEFERRED', deferrable=True, use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_code')
    )
    op.create_index('rooms_recovery', 'rooms', ['status', 'last_activity_at'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('match_no', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('tick', sa.BigInteger(), nullable=False),
    sa.Column('map_id', sa.Text(), nullable=False),
    sa.Column('map_name', sa.Text(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('latest_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('winner_match_player_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active','finished','superseded','abandoned','quarantined')", name='match_status'),
    sa.ForeignKeyConstraint(['latest_snapshot_id', 'id'], ['game_snapshots.id', 'game_snapshots.match_id'], name='match_head', initially='DEFERRED', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['winner_match_player_id', 'id'], ['match_players.id', 'match_players.match_id'], name='match_winner', initially='DEFERRED', deferrable=True, use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'room_id'),
    sa.UniqueConstraint('room_id', 'match_no')
    )
    op.create_index('one_active_match', 'matches', ['room_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('room_players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('current_pid', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("color IN ('red','blue','orange','white','green','purple')", name='member_color'),
    sa.CheckConstraint("status IN ('active','retired','revoked')", name='member_status'),
    sa.CheckConstraint('current_pid IS NULL OR current_pid BETWEEN 0 AND 5', name='member_pid'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'room_id'),
    sa.UniqueConstraint('room_id', 'current_pid')
    )
    op.create_index('room_active_color', 'room_players', ['room_id', 'color'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index('room_active_name', 'room_players', ['room_id', 'name'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('game_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.BigInteger(), nullable=False),
    sa.Column('tick', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('engine_compatibility', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'match_id'),
    sa.UniqueConstraint('match_id', 'revision')
    )
    op.create_table('match_players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('room_player_id', sa.UUID(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('consumed_seq', sa.BigInteger(), nullable=False),
    sa.Column('final_vp', sa.Integer(), nullable=True),
    sa.CheckConstraint('pid BETWEEN 0 AND 5 AND consumed_seq >= 0', name='match_player_sequence'),
    sa.ForeignKeyConstraint(['match_id', 'room_id'], ['matches.id', 'matches.room_id'], ),
    sa.ForeignKeyConstraint(['room_player_id', 'room_id'], ['room_players.id', 'room_players.room_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'match_id'),
    sa.UniqueConstraint('match_id', 'pid'),
    sa.UniqueConstraint('match_id', 'room_player_id')
    )
    op.create_table('room_operations',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('room_player_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.LargeBinary(), nullable=False),
    sa.Column('expected_epoch', sa.BigInteger(), nullable=False),
    sa.Column('result_epoch', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['room_player_id', 'room_id'], ['room_players.id', 'room_players.room_id'], ),
    sa.PrimaryKeyConstraint('room_id', 'request_id')
    )
    op.create_table('seat_tokens',
    sa.Column('room_player_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('octet_length(token_hash) = 32', name='credential_hash_length'),
    sa.ForeignKeyConstraint(['room_player_id'], ['room_players.id'], ),
    sa.PrimaryKeyConstraint('room_player_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('command_receipts',
    sa.Column('match_player_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('cmd_id', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.LargeBinary(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('result_tick', sa.BigInteger(), nullable=False),
    sa.Column('result_revision', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("outcome IN ('accepted','rejected')", name='receipt_outcome'),
    sa.ForeignKeyConstraint(['match_player_id'], ['match_players.id'], ),
    sa.PrimaryKeyConstraint('match_player_id', 'seq'),
    sa.UniqueConstraint('match_player_id', 'cmd_id')
    )
    # Cyclic aggregate references are installed after every target table exists.
    op.create_foreign_key('room_host', 'rooms', 'room_players', ['host_room_player_id','id'], ['id','room_id'], deferrable=True, initially='DEFERRED')
    op.create_foreign_key('room_current_match', 'rooms', 'matches', ['current_match_id','id'], ['id','room_id'], deferrable=True, initially='DEFERRED')
    op.create_foreign_key('match_head', 'matches', 'game_snapshots', ['latest_snapshot_id','id'], ['id','match_id'], deferrable=True, initially='DEFERRED')
    op.create_foreign_key('match_winner', 'matches', 'match_players', ['winner_match_player_id','id'], ['id','match_id'], deferrable=True, initially='DEFERRED')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('match_winner','matches', type_='foreignkey')
    op.drop_constraint('match_head','matches', type_='foreignkey')
    op.drop_constraint('room_current_match','rooms', type_='foreignkey')
    op.drop_constraint('room_host','rooms', type_='foreignkey')
    op.drop_table('command_receipts')
    op.drop_table('seat_tokens')
    op.drop_table('room_operations')
    op.drop_table('match_players')
    op.drop_table('game_snapshots')
    op.drop_index('room_active_name', table_name='room_players', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('room_active_color', table_name='room_players', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('room_players')
    op.drop_index('one_active_match', table_name='matches', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('matches')
    op.drop_index('rooms_recovery', table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
